apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: dawun4705/m-dev:nginx_v1 #nginx:1.21.1 #nginx:1.21.1 #hifrodo/msa-devops:nginx_v1
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/etc/nginx/" #사이트 접속시 css가 깨져보일 수 있으므로
          name: nginx-conf
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf   
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: NodePort