apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mywas
  template:
    metadata:
      labels:
        app: mywas
    spec:
      containers:
      - name: mywas
        image: dawun4705/flask:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000 
      initContainers:
      - name: mysql-svc
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup db-0.mysql-svc.default.svc.cluster.local; do echo waiting for db-0.mysql-svc; sleep 2; done"]

---
apiVersion: v1
kind: Service
metadata:
  name: was-svc
spec:
  selector:
    app: mywas
  #sessionAffinity: ClientIP
  ports:
  - port: 5000 
    targetPort: 5000 
  #type: LoadBalancer
