name: CICD

on:
  push:
    branches: [ main ]

jobs: 
  build:
 
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v3
   
        
    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v1 
    - name: docker ps
      run: docker ps
    - name: ls
      run: ls
    - name: docker build
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest .
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask:v1_$GITHUB_RUN_NUMBER .
        docker images
        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker push
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask:v1_$GITHUB_RUN_NUMBER
        
