name: CICD

on:
  push:
    branches: [ main ]

jobs: 
  build:
 
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pymysql
        
    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v1 
    - name: docker ps
      run: docker ps
    - name: ls
      run: ls
    - name: docker build
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest .
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask:v1_$GITHUB_RUN_NUMBER .
        docker images
        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker push
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask:v1_$GITHUB_RUN_NUMBER
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: get pod
      run: kubectl get pod
    #- name: kube_config
    #  run: aws eks update-kubeconfig --region us-west-2 --name uni
    
    
