name: CICD

on:
  push:
    branches: [ main ]

jobs: 
  build:
 
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8-slim
      uses: actions/setup-python@v2
      with:
        python-version: 3.8-slim
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask pymysql
    
    
    
